services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    environment:
      - MONGODB_ROOT_USER=docker
      - MONGODB_ROOT_PASSWORD=docker
      - MONGODB_USERNAME=docker
      - MONGODB_PASSWORD=docker
      - MONGODB_DATABASE=nest-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - local_network

  mongodb_test:
    image: bitnami/mongodb:latest
    container_name: mongodb_test
    environment:
      - MONGODB_ROOT_USER=test
      - MONGODB_ROOT_PASSWORD=test
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=test
      - MONGODB_DATABASE=nest-mongo-test
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data_test:/bitnami/mongodb
    networks:
      - local_network
  

volumes:
  mongodb_data:
    driver: local
  mongodb_data_test:
    driver: local

networks:
  local_network:
    driver: bridge
